Cleanup existingSecret

diff --git a/charts/netbox/templates/worker/Deployment.yaml b/charts/netbox/templates/worker/Deployment.yaml
--- a/charts/netbox/templates/worker/Deployment.yaml
+++ b/charts/netbox/templates/worker/Deployment.yaml
@@ -28,7 +28,7 @@ spec:
     metadata:
       annotations:
         checksum/config: {{ include (print $.Template.BasePath "/ConfigMap/netbox.yaml") . | sha256sum }}
-        {{- if (not .Values.existingSecret) }}
+        {{- if (not .Values.existingSecretName) }}
         checksum/secret: {{ include (print $.Template.BasePath "/Secret/netbox.yaml") . | sha256sum }}
         {{- end }}
         {{- if .Values.worker.podAnnotations }}
@@ -136,12 +136,54 @@ spec:
           {{- include "common.tplvalues.render" (dict "value" .Values.worker.sidecars "context" $) | nindent 8 }}
         {{- end }}
       {{- $needsVolumePermissions := and .Values.volumePermissions.enabled .Values.persistence.enabled .Values.worker.podSecurityContext.enabled .Values.worker.containerSecurityContext.enabled }}
-      {{- if or .Values.worker.initContainers $needsVolumePermissions }}
       initContainers:
+        {{- if .Values.redisWait.enabled }}
+        - name: wait-for-redis
+          image: {{ include "netbox.redis.image" . }}
+          imagePullPolicy: {{ .Values.redis.image.pullPolicy | quote }}
+          securityContext: {{- omit .Values.redisWait.containerSecurityContext "enabled" | toYaml | nindent 12 }}
+          command:
+            - /bin/bash
+          args:
+            - -ec
+            - |
+                #!/bin/bash
+
+                set -o errexit
+                set -o nounset
+                set -o pipefail
+
+                . /opt/bitnami/scripts/libos.sh
+                . /opt/bitnami/scripts/liblog.sh
+
+                check_redis_connection() {
+                  local result="$(redis-cli -h {{ include "netbox.redisHost" . }} -p {{ include "netbox.redisPort" . }} {{ .Values.redisWait.extraArgs }} PING)"
+                  if [[ "$result" != "PONG" ]]; then
+                    false
+                  fi
+                }
+
+                info "Checking redis connection..."
+                if ! retry_while "check_redis_connection"; then
+                    error "Could not connect to the Redis server"
+                    return 1
+                else
+                    info "Connected to the Redis instance"
+                fi
+          {{- if include "netbox.redis.auth.enabled" . }}
+          env:
+            - name: REDISCLI_AUTH
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "netbox.redis.secretName" . }}
+                  key: {{ include "netbox.redis.secretPasswordKey" . }}
+          {{- end }}
+        {{- end }}
+        {{- if or .Values.worker.initContainers $needsVolumePermissions }}
         {{- if .Values.worker.initContainers }}
           {{- include "common.tplvalues.render" (dict "value" .Values.worker.initContainers "context" $) | nindent 8 }}
         {{- end }}
-      {{- end }}
+        {{- end }}
       volumes:
         - name: config
           configMap:
@@ -150,10 +192,10 @@ spec:
           projected:
             sources:
             - secret:
-                name: {{ .Values.existingSecret | default (include "netbox.fullname" .) | quote }}
+                name: {{ .Values.existingSecretName | default (include "netbox.fullname" .) | quote }}
                 items:
                 # Used by our configuration
-                - key: email_password
+                - key: {{ include "netbox.email.secretPasswordKey" . | quote }}
                   path: email_password
                 - key: secret_key
                   path: secret_key
