Add redis wait

diff --git a/charts/netbox/templates/deployment.yaml b/charts/netbox/templates/deployment.yaml
--- a/charts/netbox/templates/deployment.yaml
+++ b/charts/netbox/templates/deployment.yaml
@@ -222,6 +222,48 @@ spec:
           volumeMounts:
             - name: optunit
               mountPath: /opt/unit
+        {{- if .Values.redisWait.enabled }}
+        - name: wait-for-redis
+          image: {{ include "netbox.redis.image" . }}
+          imagePullPolicy: {{ .Values.redis.image.pullPolicy | quote }}
+          securityContext: {{- omit .Values.redisWait.containerSecurityContext "enabled" | toYaml | nindent 12 }}
+          command:
+            - /bin/bash
+          args:
+            - -ec
+            - |
+                #!/bin/bash
+
+                set -o errexit
+                set -o nounset
+                set -o pipefail
+
+                . /opt/bitnami/scripts/libos.sh
+                . /opt/bitnami/scripts/liblog.sh
+
+                check_redis_connection() {
+                  local result="$(redis-cli -h {{ include "netbox.redisHost" . }} -p {{ include "netbox.redisPort" . }} {{ .Values.redisWait.extraArgs }} PING)"
+                  if [[ "$result" != "PONG" ]]; then
+                    false
+                  fi
+                }
+
+                info "Checking redis connection..."
+                if ! retry_while "check_redis_connection"; then
+                    error "Could not connect to the Redis server"
+                    return 1
+                else
+                    info "Connected to the Redis instance"
+                fi
+          {{- if include "netbox.redis.auth.enabled" . }}
+          env:
+            - name: REDISCLI_AUTH
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "netbox.redis.secretName" . }}
+                  key: {{ include "netbox.redis.secretPasswordKey" . }}
+          {{- end }}
+        {{- end }}
         {{- if or .Values.initContainers $needsVolumePermissions }}
         {{- if .Values.initContainers }}
           {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 10 }}
